# Generated by Django 4.2.21 on 2025-05-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_attendance_options_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_manager', to='main.employee'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
