# Generated by Django 4.2.21 on 2025-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_outlet_manager_outlet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='hcode',
            field=models.CharField(max_length=50),
        ),
    ]
