# Generated by Django 4.2.21 on 2025-05-25 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_holiday_hcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleave',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='confirm_date',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='confirm_done',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='confirm_user',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='hcode',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='leave_day',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='max_day_off',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='primary_location_code',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='remove_date',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='remove_done',
        ),
        migrations.RemoveField(
            model_name='empleave',
            name='remove_user',
        ),
        migrations.AddField(
            model_name='empleave',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleave',
            name='action_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_actioned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleave',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
