# Generated by Django 4.2.23 on 2025-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_empleave_add_user_remove_empleave_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='outlet',
        ),
        migrations.AddField(
            model_name='employee',
            name='outlets',
            field=models.ManyToManyField(blank=True, related_name='employees', to='main.outlet'),
        ),
    ]
