# Generated by Django 4.2.23 on 2025-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_devices_delete_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
