# Generated by Django 4.2.23 on 2025-06-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_employee_empcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='cal_epf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employ_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_cal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_com_per',
            field=models.FloatField(blank=True, default=8.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_emp_per',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='etf_com_per',
            field=models.FloatField(blank=True, default=3.0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='idnumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
