# Generated by Django 4.2.23 on 2025-06-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_employee_basic_salary_employee_cal_epf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
