# Generated by Django 4.2.23 on 2025-06-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_employee_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='epf_com_per',
            field=models.FloatField(blank=True, default=12.0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='epf_emp_per',
            field=models.FloatField(blank=True, default=8.0, null=True),
        ),
    ]
