# Generated by Django 4.2.23 on 2025-07-28 18:27

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_employee_epf_com_per_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_recognition_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='training_images_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployeeTrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.training_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_images', to='main.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
